2025-04-27 15:47:00,602 INFO    MainThread:24212 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2025-04-27 15:47:00,602 INFO    MainThread:24212 [wandb_setup.py:_flush():76] Configure stats pid to 24212
2025-04-27 15:47:00,602 INFO    MainThread:24212 [wandb_setup.py:_flush():76] Loading settings from C:\Users\ASUS\.config\wandb\settings
2025-04-27 15:47:00,602 INFO    MainThread:24212 [wandb_setup.py:_flush():76] Loading settings from D:\IIT Delhi\Projects\Adversarial games\Experimentation\codeBase\wandb\settings
2025-04-27 15:47:00,602 INFO    MainThread:24212 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-04-27 15:47:00,602 INFO    MainThread:24212 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-04-27 15:47:00,602 INFO    MainThread:24212 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'trainer.py', 'program_abspath': 'D:\\IIT Delhi\\Projects\\Adversarial games\\Experimentation\\codeBase\\trainer.py', 'program': 'D:\\IIT Delhi\\Projects\\Adversarial games\\Experimentation\\codeBase\\trainer.py'}
2025-04-27 15:47:00,603 INFO    MainThread:24212 [wandb_init.py:_log_setup():524] Logging user logs to D:\IIT Delhi\Projects\Adversarial games\Experimentation\codeBase\wandb\run-20250427_154700-juanycn7\logs\debug.log
2025-04-27 15:47:00,603 INFO    MainThread:24212 [wandb_init.py:_log_setup():525] Logging internal logs to D:\IIT Delhi\Projects\Adversarial games\Experimentation\codeBase\wandb\run-20250427_154700-juanycn7\logs\debug-internal.log
2025-04-27 15:47:00,603 INFO    MainThread:24212 [wandb_init.py:init():564] calling init triggers
2025-04-27 15:47:00,603 INFO    MainThread:24212 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2025-04-27 15:47:00,603 INFO    MainThread:24212 [wandb_init.py:init():614] starting backend
2025-04-27 15:47:00,603 INFO    MainThread:24212 [wandb_init.py:init():618] setting up manager
2025-04-27 15:47:00,608 INFO    MainThread:24212 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2025-04-27 15:47:00,610 INFO    MainThread:24212 [wandb_init.py:init():624] backend started and connected
2025-04-27 15:47:00,618 INFO    MainThread:24212 [wandb_init.py:init():716] updated telemetry
2025-04-27 15:47:00,658 INFO    MainThread:24212 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2025-04-27 15:47:01,485 ERROR   MainThread:24212 [wandb_init.py:init():775] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2025-04-27 15:47:02,073 ERROR   MainThread:24212 [wandb_init.py:init():1188] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "C:\Users\ASUS\anaconda3\envs\gpu_torch_5\Lib\site-packages\wandb\sdk\wandb_init.py", line 1170, in init
    run = wi.init()
          ^^^^^^^^^
  File "C:\Users\ASUS\anaconda3\envs\gpu_torch_5\Lib\site-packages\wandb\sdk\wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2025-04-27 15:47:03,083 WARNING MsgRouterThr:24212 [router.py:message_loop():77] message_loop has been closed
